### PR TITLE
Added reusable cla check

### PR DESCRIPTION
**Pull request by bluvulture**
https://pimcore.atlassian.net/browse/SOLI-97

Added reusable CLA check workflow
Bumped CLA action version to latest one from action release repo

example usage of new CLA within dependent workflow

> name: "CLA Assistant"
> on:
>   issue_comment:
>     types: [created]
>   pull_request_target:
>     types: [opened,closed,synchronize]
> jobs:
>   cla-check:
>       uses: pimcore/workflows-collection-public/.github/workflows/reusable-cla-check.yml@cla_check

After this PR has been merged, new release will be created and dependent workflows will reference versioned one

### CODE REVIEW

**Comment by bluvulture** [comment]
@herbertroth tested it here 
https://github.com/pimcore/saas-cypress/pull/79

**Review by herbertroth — CHANGES_REQUESTED** [review]
Shouldn't we use the CLA_ACTION_ACCESS_TOKEN instead of PRIVATE_ACCESS_TOKEN?
And update doku here: https://pimcore.atlassian.net/wiki/spaces/PD/pages/2548006917/CLA+Checker

**Comment by bluvulture** [comment]
> Shouldn't we use the CLA_ACTION_ACCESS_TOKEN instead of PRIVATE_ACCESS_TOKEN? And update doku here: https://pimcore.atlassian.net/wiki/spaces/PD/pages/2548006917/CLA+Checker

@herbertroth I thought so, but we need to stick to naming from cla checker 
https://github.com/contributor-assistant/github-action?tab=readme-ov-file#environmental-variables

**Comment by herbertroth** [comment]
> > Shouldn't we use the CLA_ACTION_ACCESS_TOKEN instead of PRIVATE_ACCESS_TOKEN? And update doku here: https://pimcore.atlassian.net/wiki/spaces/PD/pages/2548006917/CLA+Checker
> 
> @herbertroth I thought so, but we need to stick to naming from cla checker https://github.com/contributor-assistant/github-action?tab=readme-ov-file#environmental-variables


So PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_ACTION_ACCESS_TOKEN }} would also work? or do i misunderstood the doku?

**Comment by bluvulture** [comment]
> > > Shouldn't we use the CLA_ACTION_ACCESS_TOKEN instead of PRIVATE_ACCESS_TOKEN? And update doku here: https://pimcore.atlassian.net/wiki/spaces/PD/pages/2548006917/CLA+Checker
> > 
> > 
> > @herbertroth I thought so, but we need to stick to naming from cla checker https://github.com/contributor-assistant/github-action?tab=readme-ov-file#environmental-variables
> 
> So PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_ACTION_ACCESS_TOKEN }} would also work? or do i misunderstood the doku?

Would probably, but I did not want to use different names for env variable and secret.
I can try it out also, proposal just let me know.

**Review by herbertroth — APPROVED** [review]

**Pull request merged**
